"""add finance and soft delete fields

Revision ID: 26c3e15bf360
Revises: 004
Create Date: 2026-04-01 22:54:16.307625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c3e15bf360'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_org_date'), table_name='audit_logs')
    op.drop_index(op.f('ix_task_comments_created_at'), table_name='task_comments')
    op.add_column('tasks', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('record_type', sa.Enum('INCOME', 'EXPENSE', 'NEUTRAL', name='recordtype'), nullable=True))
    op.add_column('tasks', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'record_type')
    op.drop_column('tasks', 'amount')
    op.create_index(op.f('ix_task_comments_created_at'), 'task_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_date'), 'audit_logs', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
